[package]
name = "snake-in-terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.0"
error-chain = "0.12.4"
crossterm = "0.23.0"
terminal_size = "0.1.17"
derive-deref-rs = "0.1.1"
accessors-rs = "0.1.0"
tokio = { version = "1", features = ["full"] }

